name: Express Node JS Server - CI/CD
on:
      push:
        branches:
          - master
          - main
      pull_request:
        branches:
          - main
jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '20'

          - name: Install dependencies
            run: npm install

          - name: Run tests
            run: npm test

      deploy:
            name: Deploy to AWS EC2
            runs-on: ubuntu-latest
            needs: build
            steps:
              - name: Checkout code
                uses: actions/checkout@v2

              - name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                  node-version: '20'

              - name: Install dependencies
                run: npm install

              - name: rsync deployments
                uses: burnett01/rsync-deployments@5.1
                with:
                  switches: -avzr --delete
                  path: ./*
                  remote_path: "${{ secrets.TARGET_DIR }}"
                  remote_host: "${{ secrets.HOST_DNS }}"
                  remote_user: "${{ secrets.USERNAME }}"
                  remote_key: "${{ secrets.EC2_SSH_KEY }}"

 