name: Express Node JS Server - CI/CD
on:
      push:
        branches:
          - master
          - main
      pull_request:
        branches:
          - main
jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '14'

          - name: Install dependencies
            run: npm install

          - name: Run tests
            run: npm test

      deploy:
            name: Deploy to AWS EC2
            runs-on: ubuntu-latest
            needs: build
            steps:
              - name: Checkout code
                uses: actions/checkout@v2

              - name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                  node-version: '14'

              - name: Install dependencies
                run: npm install

              - name: rsync deployments
                uses: burnett01/rsync-deployments@5.1
                with:
                  switches: -avzr --delete
                  path: ./*
                  remote_path: "${{ secrets.TARGET_DIR }}"
                  remote_host: "${{ secrets.HOST_DNS }}"
                  remote_user: "${{ secrets.USERNAME }}"
                  remote_key: "${{ secrets.EC2_SSH_KEY }}"

              # - name: Deploy via SSH
              #   uses: easingthemes/ssh-deploy@main
              #   env:
              #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
              #     REMOTE_HOST: ${{ secrets.HOST_DNS }}
              #     REMOTE_USER: ${{ secrets.USERNAME }}
              #     TARGET: ${{ secrets.TARGET_DIR }}

              # - name: Build and Deploy
              #   run: |
              #     npm run build
              #     npm run deploy
              #   # Add commands to deploy your application here (e.g., using SSH, FTP, or other deployment methods)

              # - name: Deploy to AWS
              #   uses: easingthemes/ssh-deploy@v2.0.1
              #   with:
              #     server: ${{ secrets.SERVER }}
              #     remote_port: ${{ secrets.REMOTE_PORT }}
              #     remote_user: ${{ secrets.REMOTE_USER }}
              #     remote_key: ${{ secrets.REMOTE_KEY }}
              #     local_path: '.'
              #     remote_path: ${{ secrets.REMOTE_PATH }}
              #     args: '-o StrictHostKeyChecking=no'