name: Express Node JS Server - CI/CD 2024

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to app directory
      run: cd myapp

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to app directory
      run: cd myapp

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --production

    - name: Deploy via rsync
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: "${{ secrets.TARGET_DIR }}"
        remote_host: "${{ secrets.HOST_DNS }}"
        remote_user: "${{ secrets.USERNAME }}"
        remote_key: "${{ secrets.EC2_SSH_KEY }}"
