name: CI

on:
  push:
    branches: [ main ]  # Update this to match your default branch name
  pull_request:
    branches: [ main ]  # Update this to match your default branch name
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'  # Update this to match your default branch name

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*  # Update this to match your build output directory
          remote_path: "${{ secrets.TARGET_DIR }}"
          remote_host: "${{ secrets.HOST_DNS }}"
          remote_user: "${{ secrets.USERNAME }}"
          remote_key: "${{ secrets.EC2_SSH_KEY }}"
